/**
 * @xnetjs/trust — the shared provenance→trust primitives for xNet extensibility
 * (exploration 0194).
 *
 * The load-bearing invariant of the whole extensibility story: an extension's
 * trust tier follows its PROVENANCE — where it came from — never anything the
 * code declares about itself. Something you (or an AI you approved) authored
 * locally installs at the `user` tier; something pulled from a marketplace
 * installs at the `marketplace` tier (and runs in the iframe).
 *
 * Critically, when an extension node SYNCS to another device, the receiver must
 * RE-DERIVE the tier from its own local install action — never trust a tier
 * carried in the synced payload. {@link deriveTrustTier} is that single choke
 * point.
 *
 * This package exists because `@xnetjs/labs` (0180) and `@xnetjs/plugins`'s
 * ecosystem layer (0192) had *byte-for-byte identical* copies of this logic —
 * 0192 mirrored it to avoid a `plugins → labs` dependency edge (labs already
 * depends on plugins). A tiny zero-dep leaf both can depend on is the clean fix.
 * Keep it policy-only (no runtime) so it never becomes a coupling magnet.
 */

/** Where an extension came from — the only input to its trust tier. */
export type InstallProvenance =
  /** Bundled with the app. */
  | 'builtin'
  /** Authored in this workspace by the user. */
  | 'authored'
  /** Generated by an AI agent and explicitly approved by the user. */
  | 'ai-generated'
  /** Imported from a file/manifest the user pasted or opened. */
  | 'imported'
  /** Installed from a public marketplace. */
  | 'marketplace'
  /** Arrived via P2P sync from another device/peer. */
  | 'synced'

/** The execution trust tier an extension runs at. */
export type TrustTier = 'first-party' | 'user' | 'marketplace'

/** The sandbox a tier maps to (mirrors the dashboard widget tiers). */
export type SandboxKind = 'host' | 'ses-worker' | 'iframe'

/**
 * Map install provenance to a trust tier. `synced` does NOT inherit any tier —
 * it lands at `user` and the host must re-confirm capabilities locally before
 * activating (sync is not consent). `authored`/`ai-generated`/`imported` also
 * land at `user`; only `builtin` is first-party and only `marketplace` is
 * marketplace.
 */
export function deriveTrustTier(provenance: InstallProvenance): TrustTier {
  if (provenance === 'builtin') return 'first-party'
  if (provenance === 'marketplace') return 'marketplace'
  return 'user'
}

/**
 * Whether installing from `provenance` must re-prompt the user for the
 * extension's capabilities before activation. True for anything not authored on
 * this device in this session — especially synced and marketplace nodes.
 */
export function requiresCapabilityReprompt(provenance: InstallProvenance): boolean {
  return provenance !== 'builtin' && provenance !== 'authored'
}

/** Map a trust tier to the sandbox its code should run in. */
export function sandboxForTier(tier: TrustTier): SandboxKind {
  if (tier === 'first-party') return 'host'
  if (tier === 'marketplace') return 'iframe'
  return 'ses-worker'
}
