/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SocialImportRouteImport } from './routes/social-import'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DataRouteImport } from './routes/data'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewViewIdRouteImport } from './routes/view.$viewId'
import { Route as TagTagIdRouteImport } from './routes/tag.$tagId'
import { Route as SpaceSpaceIdRouteImport } from './routes/space.$spaceId'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as PersonDidRouteImport } from './routes/person.$did'
import { Route as MapMapIdRouteImport } from './routes/map.$mapId'
import { Route as LabLabIdRouteImport } from './routes/lab.$labId'
import { Route as FrameFrameSpecRouteImport } from './routes/frame.$frameSpec'
import { Route as DocDocIdRouteImport } from './routes/doc.$docId'
import { Route as DbDbIdRouteImport } from './routes/db.$dbId'
import { Route as DashboardDashboardIdRouteImport } from './routes/dashboard.$dashboardId'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as CanvasCanvasIdRouteImport } from './routes/canvas.$canvasId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialImportRoute = SocialImportRouteImport.update({
  id: '/social-import',
  path: '/social-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewViewIdRoute = ViewViewIdRouteImport.update({
  id: '/view/$viewId',
  path: '/view/$viewId',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagIdRoute = TagTagIdRouteImport.update({
  id: '/tag/$tagId',
  path: '/tag/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpaceIdRoute = SpaceSpaceIdRouteImport.update({
  id: '/space/$spaceId',
  path: '/space/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonDidRoute = PersonDidRouteImport.update({
  id: '/person/$did',
  path: '/person/$did',
  getParentRoute: () => rootRouteImport,
} as any)
const MapMapIdRoute = MapMapIdRouteImport.update({
  id: '/map/$mapId',
  path: '/map/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLabIdRoute = LabLabIdRouteImport.update({
  id: '/lab/$labId',
  path: '/lab/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameFrameSpecRoute = FrameFrameSpecRouteImport.update({
  id: '/frame/$frameSpec',
  path: '/frame/$frameSpec',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdRoute = DocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const DbDbIdRoute = DbDbIdRouteImport.update({
  id: '/db/$dbId',
  path: '/db/$dbId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIdRoute = DashboardDashboardIdRouteImport.update({
  id: '/dashboard/$dashboardId',
  path: '/dashboard/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/canvas/$canvasId',
  path: '/canvas/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/companion': typeof CompanionRoute
  '/crm': typeof CrmRoute
  '/data': typeof DataRoute
  '/discover': typeof DiscoverRoute
  '/experiments': typeof ExperimentsRoute
  '/finance': typeof FinanceRoute
  '/meetings': typeof MeetingsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/social-import': typeof SocialImportRoute
  '/stories': typeof StoriesRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/db/$dbId': typeof DbDbIdRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/frame/$frameSpec': typeof FrameFrameSpecRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/map/$mapId': typeof MapMapIdRoute
  '/person/$did': typeof PersonDidRoute
  '/post/$postId': typeof PostPostIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRoute
  '/tag/$tagId': typeof TagTagIdRoute
  '/view/$viewId': typeof ViewViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/companion': typeof CompanionRoute
  '/crm': typeof CrmRoute
  '/data': typeof DataRoute
  '/discover': typeof DiscoverRoute
  '/experiments': typeof ExperimentsRoute
  '/finance': typeof FinanceRoute
  '/meetings': typeof MeetingsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/social-import': typeof SocialImportRoute
  '/stories': typeof StoriesRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/db/$dbId': typeof DbDbIdRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/frame/$frameSpec': typeof FrameFrameSpecRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/map/$mapId': typeof MapMapIdRoute
  '/person/$did': typeof PersonDidRoute
  '/post/$postId': typeof PostPostIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRoute
  '/tag/$tagId': typeof TagTagIdRoute
  '/view/$viewId': typeof ViewViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/companion': typeof CompanionRoute
  '/crm': typeof CrmRoute
  '/data': typeof DataRoute
  '/discover': typeof DiscoverRoute
  '/experiments': typeof ExperimentsRoute
  '/finance': typeof FinanceRoute
  '/meetings': typeof MeetingsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/social-import': typeof SocialImportRoute
  '/stories': typeof StoriesRoute
  '/tasks': typeof TasksRoute
  '/welcome': typeof WelcomeRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/db/$dbId': typeof DbDbIdRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/frame/$frameSpec': typeof FrameFrameSpecRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/map/$mapId': typeof MapMapIdRoute
  '/person/$did': typeof PersonDidRoute
  '/post/$postId': typeof PostPostIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRoute
  '/tag/$tagId': typeof TagTagIdRoute
  '/view/$viewId': typeof ViewViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/companion'
    | '/crm'
    | '/data'
    | '/discover'
    | '/experiments'
    | '/finance'
    | '/meetings'
    | '/requests'
    | '/settings'
    | '/share'
    | '/social-import'
    | '/stories'
    | '/tasks'
    | '/welcome'
    | '/canvas/$canvasId'
    | '/channel/$channelId'
    | '/dashboard/$dashboardId'
    | '/db/$dbId'
    | '/doc/$docId'
    | '/frame/$frameSpec'
    | '/lab/$labId'
    | '/map/$mapId'
    | '/person/$did'
    | '/post/$postId'
    | '/space/$spaceId'
    | '/tag/$tagId'
    | '/view/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/companion'
    | '/crm'
    | '/data'
    | '/discover'
    | '/experiments'
    | '/finance'
    | '/meetings'
    | '/requests'
    | '/settings'
    | '/share'
    | '/social-import'
    | '/stories'
    | '/tasks'
    | '/welcome'
    | '/canvas/$canvasId'
    | '/channel/$channelId'
    | '/dashboard/$dashboardId'
    | '/db/$dbId'
    | '/doc/$docId'
    | '/frame/$frameSpec'
    | '/lab/$labId'
    | '/map/$mapId'
    | '/person/$did'
    | '/post/$postId'
    | '/space/$spaceId'
    | '/tag/$tagId'
    | '/view/$viewId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/companion'
    | '/crm'
    | '/data'
    | '/discover'
    | '/experiments'
    | '/finance'
    | '/meetings'
    | '/requests'
    | '/settings'
    | '/share'
    | '/social-import'
    | '/stories'
    | '/tasks'
    | '/welcome'
    | '/canvas/$canvasId'
    | '/channel/$channelId'
    | '/dashboard/$dashboardId'
    | '/db/$dbId'
    | '/doc/$docId'
    | '/frame/$frameSpec'
    | '/lab/$labId'
    | '/map/$mapId'
    | '/person/$did'
    | '/post/$postId'
    | '/space/$spaceId'
    | '/tag/$tagId'
    | '/view/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CompanionRoute: typeof CompanionRoute
  CrmRoute: typeof CrmRoute
  DataRoute: typeof DataRoute
  DiscoverRoute: typeof DiscoverRoute
  ExperimentsRoute: typeof ExperimentsRoute
  FinanceRoute: typeof FinanceRoute
  MeetingsRoute: typeof MeetingsRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SocialImportRoute: typeof SocialImportRoute
  StoriesRoute: typeof StoriesRoute
  TasksRoute: typeof TasksRoute
  WelcomeRoute: typeof WelcomeRoute
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRoute
  DashboardDashboardIdRoute: typeof DashboardDashboardIdRoute
  DbDbIdRoute: typeof DbDbIdRoute
  DocDocIdRoute: typeof DocDocIdRoute
  FrameFrameSpecRoute: typeof FrameFrameSpecRoute
  LabLabIdRoute: typeof LabLabIdRoute
  MapMapIdRoute: typeof MapMapIdRoute
  PersonDidRoute: typeof PersonDidRoute
  PostPostIdRoute: typeof PostPostIdRoute
  SpaceSpaceIdRoute: typeof SpaceSpaceIdRoute
  TagTagIdRoute: typeof TagTagIdRoute
  ViewViewIdRoute: typeof ViewViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-import': {
      id: '/social-import'
      path: '/social-import'
      fullPath: '/social-import'
      preLoaderRoute: typeof SocialImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$viewId': {
      id: '/view/$viewId'
      path: '/view/$viewId'
      fullPath: '/view/$viewId'
      preLoaderRoute: typeof ViewViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tagId': {
      id: '/tag/$tagId'
      path: '/tag/$tagId'
      fullPath: '/tag/$tagId'
      preLoaderRoute: typeof TagTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$spaceId': {
      id: '/space/$spaceId'
      path: '/space/$spaceId'
      fullPath: '/space/$spaceId'
      preLoaderRoute: typeof SpaceSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$did': {
      id: '/person/$did'
      path: '/person/$did'
      fullPath: '/person/$did'
      preLoaderRoute: typeof PersonDidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$mapId': {
      id: '/map/$mapId'
      path: '/map/$mapId'
      fullPath: '/map/$mapId'
      preLoaderRoute: typeof MapMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$labId': {
      id: '/lab/$labId'
      path: '/lab/$labId'
      fullPath: '/lab/$labId'
      preLoaderRoute: typeof LabLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frame/$frameSpec': {
      id: '/frame/$frameSpec'
      path: '/frame/$frameSpec'
      fullPath: '/frame/$frameSpec'
      preLoaderRoute: typeof FrameFrameSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId': {
      id: '/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/doc/$docId'
      preLoaderRoute: typeof DocDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$dbId': {
      id: '/db/$dbId'
      path: '/db/$dbId'
      fullPath: '/db/$dbId'
      preLoaderRoute: typeof DbDbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$dashboardId': {
      id: '/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/dashboard/$dashboardId'
      preLoaderRoute: typeof DashboardDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$canvasId': {
      id: '/canvas/$canvasId'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CompanionRoute: CompanionRoute,
  CrmRoute: CrmRoute,
  DataRoute: DataRoute,
  DiscoverRoute: DiscoverRoute,
  ExperimentsRoute: ExperimentsRoute,
  FinanceRoute: FinanceRoute,
  MeetingsRoute: MeetingsRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SocialImportRoute: SocialImportRoute,
  StoriesRoute: StoriesRoute,
  TasksRoute: TasksRoute,
  WelcomeRoute: WelcomeRoute,
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
  ChannelChannelIdRoute: ChannelChannelIdRoute,
  DashboardDashboardIdRoute: DashboardDashboardIdRoute,
  DbDbIdRoute: DbDbIdRoute,
  DocDocIdRoute: DocDocIdRoute,
  FrameFrameSpecRoute: FrameFrameSpecRoute,
  LabLabIdRoute: LabLabIdRoute,
  MapMapIdRoute: MapMapIdRoute,
  PersonDidRoute: PersonDidRoute,
  PostPostIdRoute: PostPostIdRoute,
  SpaceSpaceIdRoute: SpaceSpaceIdRoute,
  TagTagIdRoute: TagTagIdRoute,
  ViewViewIdRoute: ViewViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
