/**
 * Route tree - auto-generated by TanStack Router
 * This file is a placeholder. Run `pnpm dev` to generate the actual routes.
 */
import { Route as RootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as DocRoute } from './routes/doc.$docId'
import { Route as SettingsRoute } from './routes/settings'

// Export route tree
export const routeTree = RootRoute.addChildren([
  IndexRoute,
  DocRoute,
  SettingsRoute
])
