/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocDocIdRouteImport } from './routes/doc.$docId'
import { Route as DbDbIdRouteImport } from './routes/db.$dbId'
import { Route as CanvasCanvasIdRouteImport } from './routes/canvas.$canvasId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
} as any)
const DocDocIdRoute = DocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => rootRouteImport
} as any)
const DbDbIdRoute = DbDbIdRouteImport.update({
  id: '/db/$dbId',
  path: '/db/$dbId',
  getParentRoute: () => rootRouteImport
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/canvas/$canvasId',
  path: '/canvas/$canvasId',
  getParentRoute: () => rootRouteImport
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/db/$dbId': typeof DbDbIdRoute
  '/doc/$docId': typeof DocDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/db/$dbId': typeof DbDbIdRoute
  '/doc/$docId': typeof DocDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/db/$dbId': typeof DbDbIdRoute
  '/doc/$docId': typeof DocDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/canvas/$canvasId' | '/db/$dbId' | '/doc/$docId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/canvas/$canvasId' | '/db/$dbId' | '/doc/$docId'
  id: '__root__' | '/' | '/settings' | '/canvas/$canvasId' | '/db/$dbId' | '/doc/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
  DbDbIdRoute: typeof DbDbIdRoute
  DocDocIdRoute: typeof DocDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId': {
      id: '/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/doc/$docId'
      preLoaderRoute: typeof DocDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$dbId': {
      id: '/db/$dbId'
      path: '/db/$dbId'
      fullPath: '/db/$dbId'
      preLoaderRoute: typeof DbDbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$canvasId': {
      id: '/canvas/$canvasId'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
  DbDbIdRoute: DbDbIdRoute,
  DocDocIdRoute: DocDocIdRoute
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
