/**
 * @xnetjs/plugins — install provenance → trust tier (exploration 0192).
 *
 * This mirrors `@xnetjs/labs`'s `deriveTrustTier`/`requiresCapabilityReprompt`
 * (the canonical version for Labs/runtime code) but lives in `@xnetjs/plugins`
 * so the plugin *install path* can consult it without `@xnetjs/plugins` taking a
 * dependency on `@xnetjs/labs`. The two must agree: tier follows **provenance**
 * (where the plugin came from), never anything the manifest declares about
 * itself, and a `synced` plugin always re-derives locally — sync is not consent.
 */

/** Where a plugin came from — the only input to its trust tier. */
export type InstallProvenance =
  /** Bundled with the app. */
  | 'builtin'
  /** Authored in this workspace by the user. */
  | 'authored'
  /** Generated by an AI agent and explicitly approved by the user. */
  | 'ai-generated'
  /** Imported from a file/manifest the user pasted or opened. */
  | 'imported'
  /** Installed from a public marketplace. */
  | 'marketplace'
  /** Arrived via P2P sync from another device/peer. */
  | 'synced'

/** The execution trust tier a plugin runs at. */
export type PluginTrustTier = 'first-party' | 'user' | 'marketplace'

/**
 * Map install provenance to a trust tier. `synced` does NOT inherit any tier —
 * it lands at `user` and must re-confirm capabilities locally before activating.
 */
export function deriveTrustTier(provenance: InstallProvenance): PluginTrustTier {
  switch (provenance) {
    case 'builtin':
      return 'first-party'
    case 'authored':
    case 'ai-generated':
    case 'imported':
    case 'synced':
      return 'user'
    case 'marketplace':
      return 'marketplace'
  }
}

/**
 * Whether installing from `provenance` must re-prompt for capability consent
 * before activation. True for anything not authored on this device in this
 * session — especially synced and marketplace plugins.
 */
export function requiresCapabilityReprompt(provenance: InstallProvenance): boolean {
  return provenance !== 'builtin' && provenance !== 'authored'
}

/** The sandbox a tier maps to (mirrors the dashboard widget tiers). */
export type SandboxKind = 'host' | 'ses-worker' | 'iframe'

/** Map a trust tier to the sandbox its code should run in. */
export function sandboxForTier(tier: PluginTrustTier): SandboxKind {
  switch (tier) {
    case 'first-party':
      return 'host'
    case 'user':
      return 'ses-worker'
    case 'marketplace':
      return 'iframe'
  }
}
