/**
 * Turning fetched captions into stored nodes.
 *
 * A transcript is a `SocialContent` node with `contentKind: 'transcript'`,
 * linked back to the video it describes — not a field on the enrichment node.
 * Three reasons, in order of how much they matter:
 *
 * 1. It earns its own row in the full-text index, so an agent searching for a
 *    phrase lands on the transcript and can walk one relation to the video.
 * 2. `searchText` is capped, and transcripts routinely exceed the cap. A field
 *    would have to truncate; a node can segment.
 * 3. `transcript` was already in the content vocabulary — this is the kind
 *    finally having a producer, not a new concept.
 *
 * Segmentation is on cue boundaries, never mid-sentence, and every segment
 * records its index and the total so a partial write is visibly partial.
 */

import type { TranscriptCue } from './types'
import { createSocialNodeId } from '../import/ids'

/**
 * Characters of transcript text per node.
 *
 * `SocialContent.searchText` caps at 20 000; this leaves headroom so a segment
 * that lands slightly over a cue boundary still fits without truncation.
 */
export const TRANSCRIPT_SEGMENT_MAX_CHARS = 18_000

/** `SocialContent.textPreview` cap. */
const TEXT_PREVIEW_MAX_CHARS = 5_000

/** `SocialContent.title` cap. */
const TITLE_MAX_CHARS = 1_000

export type TranscriptSegment = {
  index: number
  startMs: number
  endMs: number
  text: string
  cueCount: number
}

export type TranscriptContentDraft = {
  /** Deterministic node id — the same transcript upserts, never duplicates. */
  id: string
  properties: {
    platform: string
    contentKind: 'transcript'
    platformContentKind: string
    platformContentId: string
    canonicalUrl?: string
    parentContent?: string
    title: string
    textPreview: string
    searchText: string
    language?: string
    publishedAt?: number
    observedAt?: number
    importedAt: number
    privacyClass: string
    visibility: string
    metadataJson: string
  }
}

/**
 * Deterministic id for one transcript segment.
 *
 * Keyed by platform, video and segment index so a re-fetch of the same video
 * lands on the same nodes rather than accumulating copies beside them.
 */
export function createSocialTranscriptId(
  platform: string,
  platformContentId: string,
  segmentIndex = 0
): string {
  return createSocialNodeId('content', [platform, 'transcript', platformContentId, segmentIndex])
}

/** Join cues into one continuous string, collapsing the gaps between them. */
export function transcriptText(cues: readonly TranscriptCue[]): string {
  return cues
    .map((cue) => cue.text.trim())
    .filter(Boolean)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Split cues into segments that each fit in one node.
 *
 * Splits happen between cues, so no segment ever ends mid-word. A single cue
 * longer than the budget gets its own oversized segment rather than being cut —
 * losing words to make a number fit is exactly the silent truncation this
 * pipeline is supposed to avoid.
 */
export function segmentTranscript(
  cues: readonly TranscriptCue[],
  maxChars = TRANSCRIPT_SEGMENT_MAX_CHARS
): TranscriptSegment[] {
  const usable = cues.filter((cue) => cue.text.trim().length > 0)
  if (usable.length === 0) return []

  const segments: TranscriptSegment[] = []
  let current: TranscriptCue[] = []
  let currentLength = 0

  const flush = (): void => {
    if (current.length === 0) return

    const first = current[0]
    const last = current[current.length - 1]
    if (!first || !last) return

    segments.push({
      index: segments.length,
      startMs: first.startMs,
      endMs: last.startMs + last.durationMs,
      text: transcriptText(current),
      cueCount: current.length
    })
    current = []
    currentLength = 0
  }

  for (const cue of usable) {
    const text = cue.text.trim()
    const addition = currentLength === 0 ? text.length : text.length + 1

    if (currentLength > 0 && currentLength + addition > maxChars) {
      flush()
    }

    current.push(cue)
    currentLength += currentLength === 0 ? text.length : text.length + 1
  }

  flush()
  return segments
}

function clamp(value: string, max: number): string {
  return value.length <= max ? value : value.slice(0, max)
}

function assignDefined<T extends object, K extends keyof T>(
  target: T,
  key: K,
  value: T[K] | undefined
): void {
  if (value !== undefined) target[key] = value
}

export type TranscriptContentDraftInput = {
  platform: string
  platformContentId: string
  /** Node id of the video this transcript describes. */
  videoNodeId?: string
  /** Title of the video, used to name the transcript node. */
  videoTitle?: string
  canonicalUrl?: string
  cues: readonly TranscriptCue[]
  language?: string
  autoGenerated?: boolean
  /** Epoch ms the fetch completed. */
  fetchedAtMs: number
  publishedAtMs?: number
  /**
   * Privacy class for the stored transcript. Defaults to `public`, which is
   * correct for a published video's captions and wrong for anything else —
   * callers importing from a private source must say so.
   */
  privacyClass?: string
}

/**
 * Build the node drafts for one video's transcript.
 *
 * Returns one draft per segment, in order. An empty cue list returns `[]`
 * rather than an empty node: "we fetched nothing" is not a transcript.
 */
export function createTranscriptContentDrafts(
  input: TranscriptContentDraftInput
): TranscriptContentDraft[] {
  const segments = segmentTranscript(input.cues)
  if (segments.length === 0) return []

  const baseTitle = input.videoTitle?.trim() || `${input.platform} ${input.platformContentId}`

  return segments.map((segment) => {
    const suffix = segments.length > 1 ? ` (part ${segment.index + 1}/${segments.length})` : ''
    const title = clamp(`Transcript — ${baseTitle}${suffix}`, TITLE_MAX_CHARS)

    const properties: TranscriptContentDraft['properties'] = {
      platform: input.platform,
      contentKind: 'transcript',
      platformContentKind: input.autoGenerated ? 'transcript-asr' : 'transcript',
      platformContentId: input.platformContentId,
      title,
      textPreview: clamp(segment.text, TEXT_PREVIEW_MAX_CHARS),
      searchText: segment.text,
      importedAt: input.fetchedAtMs,
      observedAt: input.fetchedAtMs,
      privacyClass: input.privacyClass ?? 'public',
      visibility: 'private',
      metadataJson: JSON.stringify({
        transcript: {
          segmentIndex: segment.index,
          segmentCount: segments.length,
          startMs: segment.startMs,
          endMs: segment.endMs,
          cueCount: segment.cueCount,
          autoGenerated: input.autoGenerated ?? false,
          ...(input.language ? { language: input.language } : {})
        }
      })
    }

    assignDefined(properties, 'canonicalUrl', input.canonicalUrl)
    assignDefined(properties, 'parentContent', input.videoNodeId)
    assignDefined(properties, 'language', input.language)
    assignDefined(properties, 'publishedAt', input.publishedAtMs)

    return {
      id: createSocialTranscriptId(input.platform, input.platformContentId, segment.index),
      properties
    }
  })
}
