import { describe, expect, it } from 'vitest'
import {
  createSocialTranscriptId,
  createTranscriptContentDrafts,
  createYouTubeTranscriptFetcher,
  describeTranscriptRun,
  enrichmentStatusForTranscriptOutcome,
  parseYouTubeJson3Transcript,
  parseYouTubeXmlTranscript,
  runTranscriptFetchPass,
  segmentTranscript,
  summarizeTranscriptRun,
  transcriptStateForEnrichmentStatus,
  youTubeTimedTextUrl,
  type TranscriptCue,
  type TranscriptTarget
} from './index'

function cue(startMs: number, text: string, durationMs = 1000): TranscriptCue {
  return { startMs, durationMs, text }
}

function jsonResponse(body: string, status = 200): Response {
  return new Response(body, { status })
}

describe('youtube caption parsing', () => {
  it('joins json3 segments into one cue each', () => {
    const body = JSON.stringify({
      events: [
        { tStartMs: 0, dDurationMs: 1500, segs: [{ utf8: 'hello ' }, { utf8: 'world' }] },
        { tStartMs: 1500, dDurationMs: 900, segs: [{ utf8: 'again' }] },
        { tStartMs: 2400, dDurationMs: 100, segs: [{ utf8: '  ' }] }
      ]
    })

    expect(parseYouTubeJson3Transcript(body)).toEqual([
      { startMs: 0, durationMs: 1500, text: 'hello world' },
      { startMs: 1500, durationMs: 900, text: 'again' }
    ])
  })

  it('returns no cues for a malformed payload rather than throwing', () => {
    expect(parseYouTubeJson3Transcript('not json')).toEqual([])
  })

  it('decodes entities and strips markup from the xml format', () => {
    const body =
      '<transcript><text start="0" dur="1.5">Bread &amp; butter</text>' +
      '<text start="1.5" dur="2">it&#39;s <b>rising</b></text></transcript>'

    expect(parseYouTubeXmlTranscript(body)).toEqual([
      { startMs: 0, durationMs: 1500, text: 'Bread & butter' },
      { startMs: 1500, durationMs: 2000, text: "it's rising" }
    ])
  })

  it('selects the auto-generated track with kind=asr', () => {
    const url = new URL(youTubeTimedTextUrl({ videoId: 'abc123', autoGenerated: true }))
    expect(url.searchParams.get('v')).toBe('abc123')
    expect(url.searchParams.get('kind')).toBe('asr')
    expect(new URL(youTubeTimedTextUrl({ videoId: 'abc123' })).searchParams.get('kind')).toBeNull()
  })
})

describe('youtube transcript fetcher', () => {
  const target: TranscriptTarget = { platform: 'youtube', platformContentId: 'abc123' }

  it('falls back from the author track to the auto-generated one', async () => {
    const urls: string[] = []
    const fetcher = createYouTubeTranscriptFetcher({
      fetchImpl: (async (input: string) => {
        urls.push(String(input))
        if (!String(input).includes('kind=asr')) return jsonResponse('')
        return jsonResponse(
          JSON.stringify({ events: [{ tStartMs: 0, dDurationMs: 500, segs: [{ utf8: 'hi' }] }] })
        )
      }) as unknown as typeof fetch
    })

    const outcome = await fetcher.fetch(target)
    expect(outcome.status).toBe('fetched')
    expect(urls).toHaveLength(2)
    if (outcome.status === 'fetched') {
      expect(outcome.autoGenerated).toBe(true)
      expect(outcome.cues).toEqual([{ startMs: 0, durationMs: 500, text: 'hi' }])
    }
  })

  it('reports an empty track as no-captions, not as an error', async () => {
    const fetcher = createYouTubeTranscriptFetcher({
      fetchImpl: (async () => jsonResponse('')) as unknown as typeof fetch
    })

    expect((await fetcher.fetch(target)).status).toBe('no-captions')
  })

  it('reports a refusal as blocked and stops trying other tracks', async () => {
    let calls = 0
    const fetcher = createYouTubeTranscriptFetcher({
      fetchImpl: (async () => {
        calls += 1
        return jsonResponse('', 429)
      }) as unknown as typeof fetch,
      languages: ['en', 'de']
    })

    const outcome = await fetcher.fetch(target)
    expect(outcome.status).toBe('blocked')
    expect(calls).toBe(1)
  })

  it('reports a thrown transport failure as an error', async () => {
    const fetcher = createYouTubeTranscriptFetcher({
      fetchImpl: (async () => {
        throw new Error('offline')
      }) as unknown as typeof fetch
    })

    const outcome = await fetcher.fetch(target)
    expect(outcome).toEqual({ status: 'error', reason: 'offline' })
  })
})

describe('transcript segmentation', () => {
  it('splits on cue boundaries and never mid-word', () => {
    const cues = [cue(0, 'a'.repeat(30)), cue(1000, 'b'.repeat(30)), cue(2000, 'c'.repeat(30))]
    const segments = segmentTranscript(cues, 70)

    expect(segments).toHaveLength(2)
    expect(segments[0]?.text).toBe(`${'a'.repeat(30)} ${'b'.repeat(30)}`)
    expect(segments[1]?.text).toBe('c'.repeat(30))
    expect(segments[1]?.startMs).toBe(2000)
  })

  it('keeps a single oversized cue whole rather than truncating it', () => {
    const segments = segmentTranscript([cue(0, 'x'.repeat(500))], 100)
    expect(segments).toHaveLength(1)
    expect(segments[0]?.text).toHaveLength(500)
  })

  it('drops empty cues', () => {
    expect(segmentTranscript([cue(0, '   ')])).toEqual([])
  })
})

describe('transcript content drafts', () => {
  const base = {
    platform: 'youtube',
    platformContentId: 'abc123',
    videoNodeId: 'social:content:video',
    videoTitle: 'Sourdough basics',
    canonicalUrl: 'https://www.youtube.com/watch?v=abc123',
    fetchedAtMs: 1_700_000_000_000
  }

  it('links each segment back to the video and stays deterministic', () => {
    const drafts = createTranscriptContentDrafts({ ...base, cues: [cue(0, 'mix the flour')] })

    expect(drafts).toHaveLength(1)
    expect(drafts[0]?.id).toBe(createSocialTranscriptId('youtube', 'abc123', 0))
    expect(drafts[0]?.properties.parentContent).toBe('social:content:video')
    expect(drafts[0]?.properties.contentKind).toBe('transcript')
    expect(drafts[0]?.properties.searchText).toBe('mix the flour')

    const again = createTranscriptContentDrafts({ ...base, cues: [cue(0, 'mix the flour')] })
    expect(again[0]?.id).toBe(drafts[0]?.id)
  })

  it('numbers multi-part transcripts and records the segment count', () => {
    const cues = Array.from({ length: 6 }, (_, index) => cue(index * 1000, 'word '.repeat(1000)))
    const drafts = createTranscriptContentDrafts({ ...base, cues })

    expect(drafts.length).toBeGreaterThan(1)
    expect(drafts[0]?.properties.title).toContain(`part 1/${drafts.length}`)
    for (const draft of drafts) {
      expect(draft.properties.searchText.length).toBeLessThanOrEqual(20_000)
      const metadata = JSON.parse(draft.properties.metadataJson) as {
        transcript: { segmentCount: number }
      }
      expect(metadata.transcript.segmentCount).toBe(drafts.length)
    }
  })

  it('returns nothing for an empty transcript', () => {
    expect(createTranscriptContentDrafts({ ...base, cues: [] })).toEqual([])
  })

  it('marks an auto-generated track in the platform content kind', () => {
    const drafts = createTranscriptContentDrafts({
      ...base,
      cues: [cue(0, 'hello')],
      autoGenerated: true
    })
    expect(drafts[0]?.properties.platformContentKind).toBe('transcript-asr')
  })
})

describe('run states', () => {
  it('keeps no-captions, blocked and not-attempted distinguishable', () => {
    expect(enrichmentStatusForTranscriptOutcome('no-captions')).toBe('unavailable')
    expect(enrichmentStatusForTranscriptOutcome('blocked')).toBe('blocked')
    expect(transcriptStateForEnrichmentStatus('unavailable')).toBe('no-captions')
    expect(transcriptStateForEnrichmentStatus('blocked')).toBe('blocked')
    expect(transcriptStateForEnrichmentStatus(undefined)).toBe('not-attempted')
  })

  it('counts unattempted targets so the states sum to the total', () => {
    const summary = summarizeTranscriptRun({
      states: ['fetched', 'fetched', 'no-captions', 'blocked'],
      total: 50
    })

    expect(summary.total).toBe(50)
    expect(
      summary.fetched +
        summary.noCaptions +
        summary.blocked +
        summary.errored +
        summary.notAttempted
    ).toBe(50)
    expect(summary.notAttempted).toBe(46)
    expect(summary.complete).toBe(false)
    expect(summary.retryable).toBe(true)
  })

  it('reports a run that reached every target as complete', () => {
    const summary = summarizeTranscriptRun({ states: ['fetched', 'no-captions'], total: 2 })
    expect(summary.complete).toBe(true)
    expect(summary.retryable).toBe(false)
    expect(describeTranscriptRun(summary)).toBe(
      '2 videos, complete: 1 fetched, 1 without captions.'
    )
  })

  it('names the untried remainder in the description', () => {
    const summary = summarizeTranscriptRun({ states: ['blocked'], total: 10 })
    expect(describeTranscriptRun(summary)).toContain('9 not attempted')
    expect(describeTranscriptRun(summary)).toContain('incomplete')
  })
})

describe('transcript pass', () => {
  const targets: TranscriptTarget[] = Array.from({ length: 5 }, (_, index) => ({
    platform: 'youtube',
    platformContentId: `video-${index}`
  }))

  function fetcherReturning(outcomes: readonly string[]) {
    let index = 0
    return {
      platform: 'youtube',
      supports: () => true,
      fetch: async () => {
        const status = outcomes[Math.min(index++, outcomes.length - 1)] ?? 'no-captions'
        if (status === 'fetched') {
          return { status: 'fetched' as const, cues: [cue(0, 'hi')] }
        }
        return { status: status as 'no-captions' | 'blocked' | 'error', reason: 'test' }
      }
    }
  }

  it('paces attempts and records every outcome', async () => {
    const delays: number[] = []
    const seen: string[] = []

    const result = await runTranscriptFetchPass({
      targets,
      fetcher: fetcherReturning(['fetched']),
      onResult: (target, outcome) => {
        seen.push(`${target.platformContentId}:${outcome.status}`)
      },
      delayFn: async (ms) => {
        delays.push(ms)
      },
      random: () => 0.5,
      intervalMs: 1000,
      jitterMs: 400
    })

    expect(seen).toHaveLength(5)
    expect(delays).toEqual([1200, 1200, 1200, 1200])
    expect(result.summary.complete).toBe(true)
    expect(result.summary.fetched).toBe(5)
    expect(result.stoppedEarly).toBe(false)
  })

  it('gives up after consecutive refusals and reports the run incomplete', async () => {
    const result = await runTranscriptFetchPass({
      targets,
      fetcher: fetcherReturning(['blocked']),
      onResult: () => {},
      delayFn: async () => {},
      random: () => 0,
      maxConsecutiveBlocks: 2
    })

    expect(result.stoppedEarly).toBe(true)
    expect(result.summary.blocked).toBe(2)
    expect(result.summary.notAttempted).toBe(3)
    expect(result.summary.complete).toBe(false)
    expect(result.retryable).toHaveLength(2)
  })

  it('accounts for every video in a 50-item playlist run', async () => {
    // The shape of a real pass, with the transport stubbed: a mixed playlist
    // where some videos have captions, some do not, and one request fails.
    const playlist: TranscriptTarget[] = Array.from({ length: 50 }, (_, index) => ({
      platform: 'youtube',
      platformContentId: `playlist-video-${index}`
    }))
    const drafts: string[] = []
    let index = 0

    const result = await runTranscriptFetchPass({
      targets: playlist,
      fetcher: {
        platform: 'youtube',
        supports: () => true,
        fetch: async () => {
          const position = index++
          if (position % 10 === 7) return { status: 'no-captions' as const }
          if (position === 23) return { status: 'error' as const, reason: 'timeout' }
          return { status: 'fetched' as const, cues: [cue(0, `line ${position}`)] }
        }
      },
      onResult: (target, outcome) => {
        if (outcome.status !== 'fetched') return
        for (const draft of createTranscriptContentDrafts({
          platform: target.platform,
          platformContentId: target.platformContentId,
          cues: outcome.cues,
          fetchedAtMs: 1_700_000_000_000
        })) {
          drafts.push(draft.id)
        }
      },
      delayFn: async () => {},
      random: () => 0
    })

    const { summary } = result
    expect(summary.total).toBe(50)
    expect(
      summary.fetched +
        summary.noCaptions +
        summary.blocked +
        summary.errored +
        summary.notAttempted
    ).toBe(50)
    expect(summary.fetched).toBe(44)
    expect(summary.noCaptions).toBe(5)
    expect(summary.errored).toBe(1)
    expect(summary.notAttempted).toBe(0)
    expect(summary.complete).toBe(true)
    expect(describeTranscriptRun(summary)).toContain('complete')

    // One transcript node per fetched video, each with a distinct id.
    expect(drafts).toHaveLength(44)
    expect(new Set(drafts).size).toBe(44)
  })

  it('leaves unsupported targets unattempted rather than counting them as misses', async () => {
    const result = await runTranscriptFetchPass({
      targets: [
        { platform: 'youtube', platformContentId: 'a' },
        { platform: 'tiktok', platformContentId: 'b' }
      ],
      fetcher: {
        platform: 'youtube',
        supports: (target) => target.platform === 'youtube',
        fetch: async () => ({ status: 'fetched', cues: [cue(0, 'hi')] })
      },
      onResult: () => {},
      delayFn: async () => {}
    })

    expect(result.summary.fetched).toBe(1)
    expect(result.summary.notAttempted).toBe(1)
    expect(result.summary.complete).toBe(false)
  })
})
