/**
 * The transcript fetch seam (exploration 0419).
 *
 * Transcripts are the one part of the social atlas that cannot come out of an
 * archive: no platform export ships them, and the official caption APIs only
 * serve videos you own. What is left is the unofficial caption endpoint each
 * platform's own player uses — which is blocked from datacenter address ranges
 * and is not blocked from the device the user watches on.
 *
 * That asymmetry is why this is a seam rather than a hub route. A fetch issued
 * from the user's own machine, for a video that user demonstrably saved, at a
 * human pace, is the same request their browser would make. Routing it through
 * a shared server would be slower, more fragile, and would turn a local read
 * into someone else's egress.
 *
 * The contract is deliberately total: every attempt ends in exactly one of four
 * outcomes, and "no captions exist" is a different value from "we were refused"
 * and from "we have not looked yet". A pipeline that collapsed those would
 * report a blocked run as a complete one.
 */

/** A video we can attempt a transcript for. */
export type TranscriptTarget = {
  /** Platform id, matching `socialPlatforms` (`youtube`, `tiktok`, …). */
  platform: string
  /** The platform's own id for the video (not the xNet node id). */
  platformContentId: string
  /** Canonical watch URL, when known. */
  url?: string
  /** BCP-47 language preference, best-effort. */
  preferredLanguage?: string
}

/** One timed line of a transcript. */
export type TranscriptCue = {
  /** Cue start in milliseconds from the beginning of the video. */
  startMs: number
  /** Cue duration in milliseconds; 0 when the source does not say. */
  durationMs: number
  text: string
}

/**
 * The result of one attempt.
 *
 * `no-captions` and `blocked` are both "we got nothing", and keeping them
 * apart is the whole point: the first is a fact about the video and will not
 * change on retry, the second is a fact about us and will.
 */
export type TranscriptFetchOutcome =
  | {
      status: 'fetched'
      cues: TranscriptCue[]
      /** Language actually returned, when the source declares one. */
      language?: string
      /** True when the track is machine-generated rather than author-supplied. */
      autoGenerated?: boolean
    }
  | { status: 'no-captions'; reason?: string }
  | { status: 'blocked'; reason?: string }
  | { status: 'error'; reason: string }

export type TranscriptFetchStatus = TranscriptFetchOutcome['status']

/**
 * A per-platform transcript source.
 *
 * Implementations must not throw for an expected miss — a video without
 * captions returns `no-captions`, and a refusal returns `blocked`. Throwing is
 * reserved for programmer error.
 */
export interface TranscriptFetcher {
  /** Platform this fetcher serves. */
  readonly platform: string
  /** Whether this fetcher can attempt the given target at all. */
  supports(target: TranscriptTarget): boolean
  fetch(target: TranscriptTarget, signal?: AbortSignal): Promise<TranscriptFetchOutcome>
}

/**
 * Map a fetch outcome onto the persisted `SocialEnrichment.status` vocabulary.
 *
 * The mapping is total and lossless in the direction that matters: each of the
 * four outcomes lands on a distinct stored status, so a later count over stored
 * nodes can reconstruct what happened without re-fetching.
 */
export function enrichmentStatusForTranscriptOutcome(
  status: TranscriptFetchStatus
): 'resolved' | 'unavailable' | 'blocked' | 'error' {
  switch (status) {
    case 'fetched':
      return 'resolved'
    case 'no-captions':
      return 'unavailable'
    case 'blocked':
      return 'blocked'
    case 'error':
      return 'error'
  }
}

/** True when another attempt could plausibly succeed. */
export function isRetryableTranscriptStatus(status: TranscriptFetchStatus): boolean {
  return status === 'blocked' || status === 'error'
}
