/**
 * YouTube transcript fetching over the player's own caption endpoint.
 *
 * Parsing is separated from fetching on purpose: the wire formats are stable
 * and testable, the transport is neither. Everything below the fetcher is a
 * pure function over a string, so the fragile part is one small surface.
 */

import type {
  TranscriptCue,
  TranscriptFetchOutcome,
  TranscriptFetcher,
  TranscriptTarget
} from './types'

const TIMEDTEXT_ENDPOINT = 'https://www.youtube.com/api/timedtext'

/** Status codes that mean "you, not the video" — worth retrying later. */
const BLOCKED_STATUS_CODES = new Set([401, 403, 407, 429, 500, 502, 503, 504])

export type YouTubeTimedTextFormat = 'json3' | 'xml'

/**
 * The `json3` payload shape, reduced to what we read.
 *
 * `segs` is the word/phrase split inside a cue; joining it is what turns an
 * auto-generated track back into a sentence.
 */
type Json3Payload = {
  events?: Array<{
    tStartMs?: number
    dDurationMs?: number
    segs?: Array<{ utf8?: string }>
  }>
}

function normalizeCueText(value: string): string {
  return value.replace(/\s+/g, ' ').trim()
}

/** Decode the small set of XML entities the caption track actually uses. */
function decodeXmlEntities(value: string): string {
  return value
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code: string) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&')
}

/** Parse the `fmt=json3` caption payload. Returns `[]` for an empty track. */
export function parseYouTubeJson3Transcript(body: string): TranscriptCue[] {
  let payload: Json3Payload
  try {
    payload = JSON.parse(body) as Json3Payload
  } catch {
    return []
  }

  const cues: TranscriptCue[] = []
  for (const event of payload.events ?? []) {
    const text = normalizeCueText((event.segs ?? []).map((seg) => seg.utf8 ?? '').join(''))
    if (!text) continue

    cues.push({
      startMs: Math.max(0, Math.round(event.tStartMs ?? 0)),
      durationMs: Math.max(0, Math.round(event.dDurationMs ?? 0)),
      text
    })
  }

  return cues
}

/** Parse the legacy `<transcript><text start dur>` caption payload. */
export function parseYouTubeXmlTranscript(body: string): TranscriptCue[] {
  const cues: TranscriptCue[] = []
  const pattern = /<text\b([^>]*)>([\s\S]*?)<\/text>/g

  for (const match of body.matchAll(pattern)) {
    const attributes = match[1] ?? ''
    const text = normalizeCueText(decodeXmlEntities(match[2] ?? '').replace(/<[^>]+>/g, ''))
    if (!text) continue

    const start = Number(/\bstart="([^"]*)"/.exec(attributes)?.[1] ?? '0')
    const duration = Number(/\bdur="([^"]*)"/.exec(attributes)?.[1] ?? '0')

    cues.push({
      startMs: Number.isFinite(start) ? Math.max(0, Math.round(start * 1000)) : 0,
      durationMs: Number.isFinite(duration) ? Math.max(0, Math.round(duration * 1000)) : 0,
      text
    })
  }

  return cues
}

/** Parse either caption wire format, picking by content rather than by flag. */
export function parseYouTubeTranscript(body: string): TranscriptCue[] {
  const trimmed = body.trim()
  if (!trimmed) return []
  if (trimmed.startsWith('{')) return parseYouTubeJson3Transcript(trimmed)
  return parseYouTubeXmlTranscript(trimmed)
}

export function youTubeTimedTextUrl(input: {
  videoId: string
  language?: string
  format?: YouTubeTimedTextFormat
  autoGenerated?: boolean
}): string {
  const url = new URL(TIMEDTEXT_ENDPOINT)
  url.searchParams.set('v', input.videoId)
  url.searchParams.set('lang', input.language ?? 'en')
  url.searchParams.set('fmt', input.format ?? 'json3')
  // `kind=asr` selects the machine-generated track; author-supplied tracks are
  // served without it, so the two are separate requests rather than a fallback
  // inside one.
  if (input.autoGenerated) url.searchParams.set('kind', 'asr')
  return url.toString()
}

export type YouTubeTranscriptFetcherOptions = {
  fetchImpl?: typeof fetch
  /** Languages to try, in order. Defaults to English. */
  languages?: readonly string[]
}

/**
 * Classify a transport failure.
 *
 * An empty 200 means the track does not exist; a 403/429 means we were refused.
 * Conflating them would make a rate-limited run look like a library of videos
 * that simply have no captions.
 */
function outcomeForResponse(status: number): TranscriptFetchOutcome | null {
  if (status === 404) return { status: 'no-captions', reason: 'caption track not found' }
  if (BLOCKED_STATUS_CODES.has(status)) {
    return { status: 'blocked', reason: `caption request refused with ${status}` }
  }
  if (status >= 400) return { status: 'error', reason: `caption request failed with ${status}` }
  return null
}

/**
 * Device-local YouTube transcript fetcher.
 *
 * Tries the author-supplied track first and the auto-generated one second, per
 * language. The first non-empty track wins; a clean miss on every combination
 * is `no-captions`, and a refusal anywhere short-circuits to `blocked` so the
 * queue can back off instead of burning through the rest of the list.
 */
export function createYouTubeTranscriptFetcher(
  options: YouTubeTranscriptFetcherOptions = {}
): TranscriptFetcher {
  const fetchImpl = options.fetchImpl ?? fetch
  const languages = options.languages?.length ? options.languages : ['en']

  return {
    platform: 'youtube',

    supports(target: TranscriptTarget): boolean {
      return target.platform === 'youtube' && Boolean(target.platformContentId)
    },

    async fetch(target: TranscriptTarget, signal?: AbortSignal): Promise<TranscriptFetchOutcome> {
      const preferred = target.preferredLanguage
      const ordered = preferred
        ? [preferred, ...languages.filter((l) => l !== preferred)]
        : languages

      for (const language of ordered) {
        for (const autoGenerated of [false, true]) {
          const url = youTubeTimedTextUrl({
            videoId: target.platformContentId,
            language,
            autoGenerated
          })

          let response: Response
          try {
            response = await fetchImpl(url, signal ? { signal } : {})
          } catch (error) {
            return {
              status: 'error',
              reason: error instanceof Error ? error.message : 'caption request threw'
            }
          }

          const failure = outcomeForResponse(response.status)
          // A refusal is about us and applies to every remaining combination.
          if (failure?.status === 'blocked') return failure
          if (failure?.status === 'error') return failure
          if (failure) continue

          const body = await response.text().catch(() => '')
          const cues = parseYouTubeTranscript(body)
          if (cues.length === 0) continue

          return {
            status: 'fetched',
            cues,
            language,
            autoGenerated
          }
        }
      }

      return { status: 'no-captions', reason: 'no caption track for the requested languages' }
    }
  }
}
