/**
 * Trust derivation (exploration 0180).
 *
 * The load-bearing invariant of the whole extensibility story: a Lab/extension's
 * trust tier follows its PROVENANCE — where it came from — never anything the
 * code declares about itself. A Lab you (or an AI you approved) authored locally
 * installs at the `user` tier; something pulled from a marketplace installs at
 * the `marketplace` tier (and gets the iframe).
 *
 * Critically, when a Lab/extension node SYNCS to another device, the receiver
 * must RE-DERIVE the tier from its own local install action — never trust a tier
 * carried in the synced payload. {@link deriveTrustTier} is that single choke
 * point.
 */

import type { LabTrustTier } from './runtime/types'

export type LabInstallSource =
  /** Bundled with the app. */
  | 'builtin'
  /** Authored in this workspace by the user. */
  | 'authored'
  /** Generated by an AI agent and explicitly approved by the user. */
  | 'ai-generated'
  /** Imported from a file/manifest the user pasted or opened. */
  | 'imported'
  /** Installed from a public marketplace. */
  | 'marketplace'
  /** Arrived via P2P sync from another device/peer. */
  | 'synced'

/**
 * Map an install source to a trust tier. Note that `synced` does NOT inherit
 * any tier — it always lands at `user` and the host must re-confirm
 * capabilities locally before activating (sync is not consent).
 */
export function deriveTrustTier(source: LabInstallSource): LabTrustTier {
  switch (source) {
    case 'builtin':
      return 'first-party'
    case 'authored':
    case 'ai-generated':
    case 'imported':
    case 'synced':
      return 'user'
    case 'marketplace':
      return 'marketplace'
  }
}

/**
 * Whether installing from `source` must re-prompt the user for the extension's
 * capabilities before activation. True for anything not authored on this device
 * in this session — especially synced nodes.
 */
export function requiresCapabilityReprompt(source: LabInstallSource): boolean {
  return source !== 'builtin' && source !== 'authored'
}
