/**
 * Lens Code Generator - Generate migration lens code from schema diff.
 *
 * This utility generates TypeScript code for schema migration lenses
 * based on the detected changes between two schema versions.
 */

import type { SchemaDiffResult, SchemaChange } from './schema-diff.js'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface GenerateLensOptions {
  /** The schema diff result */
  diff: SchemaDiffResult
  /** Source schema IRI */
  sourceIRI: string
  /** Target schema IRI */
  targetIRI: string
  /** Whether to include comments */
  includeComments?: boolean
  /** Whether to include TODO markers for manual fixes */
  includeTodos?: boolean
}

export interface GeneratedLens {
  /** The generated TypeScript code */
  code: string
  /** Whether the generated lens is complete (no TODOs) */
  isComplete: boolean
  /** List of items that need manual attention */
  manualItems: string[]
}

// ─── Code Generation ─────────────────────────────────────────────────────────

function indent(code: string, level: number): string {
  const spaces = '  '.repeat(level)
  return code
    .split('\n')
    .map((line) => (line.trim() ? spaces + line : line))
    .join('\n')
}

function generateOperationCode(change: SchemaChange): string | null {
  if (!change.suggestedLens) return null
  if (change.suggestedLens.startsWith('// TODO')) return null
  return change.suggestedLens
}

function generateComment(change: SchemaChange): string {
  const riskBadge =
    change.risk === 'breaking'
      ? '// BREAKING: '
      : change.risk === 'caution'
        ? '// CAUTION: '
        : '// '
  return `${riskBadge}${change.description}`
}

/**
 * Generate migration lens code from a schema diff.
 */
export function generateLensCode(options: GenerateLensOptions): GeneratedLens {
  const { diff, sourceIRI, targetIRI, includeComments = true, includeTodos = true } = options

  const operations: string[] = []
  const manualItems: string[] = []
  let isComplete = true

  // Process each change
  for (const change of diff.changes) {
    // Skip safe changes without lens operations
    if (change.risk === 'safe' && !change.suggestedLens) {
      continue
    }

    const operationCode = generateOperationCode(change)

    if (operationCode) {
      if (includeComments) {
        operations.push(generateComment(change))
      }
      operations.push(operationCode + ',')
    } else if (change.risk !== 'safe') {
      // Needs manual attention
      isComplete = false
      manualItems.push(change.description)

      if (includeTodos) {
        operations.push(`// TODO: ${change.description}`)
        if (change.suggestedLens) {
          operations.push(change.suggestedLens)
        }
        operations.push(`// transform('${change.property}', (v) => /* ... */, (v) => /* ... */),`)
      }
    }
  }

  // Generate the full file
  const code = `/**
 * Migration lens: ${sourceIRI} -> ${targetIRI}
 *
 * Generated by: xnet migrate generate
 * Risk level: ${diff.overallRisk.toUpperCase()}
 * Changes: ${diff.summary.safe} safe, ${diff.summary.caution} caution, ${diff.summary.breaking} breaking
 *${!isComplete ? '\n * NOTE: This lens requires manual completion. See TODO comments below.' : ''}
 */

import { composeLens, rename, convert, addDefault, remove, transform } from '@xnet/data'
import type { SchemaIRI } from '@xnet/data'

const SOURCE: SchemaIRI = '${sourceIRI}' as SchemaIRI
const TARGET: SchemaIRI = '${targetIRI}' as SchemaIRI

/**
 * Migrate from ${sourceIRI.split('@')[0].split('/').pop()}@${diff.fromVersion} to @${diff.toVersion}
 */
export const lens = composeLens(
  SOURCE,
  TARGET,
${indent(operations.join('\n'), 1)}
)

export default lens
`

  return {
    code,
    isComplete,
    manualItems
  }
}

/**
 * Generate a simple lens code snippet (without full file).
 */
export function generateLensSnippet(diff: SchemaDiffResult): string {
  const operations: string[] = []

  for (const change of diff.changes) {
    const operationCode = generateOperationCode(change)
    if (operationCode) {
      operations.push(operationCode)
    }
  }

  if (operations.length === 0) {
    return '// No migration operations needed'
  }

  return `composeLens(\n${indent(operations.join(',\n'), 1)}\n)`
}
